name: Build AttendBot APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Yeh khud-ba-khud latest stable version uthaye ga taake webview chal sake
          cache: true

      - name: Clean Project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos
        continue-on-error: true

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK
        uses: actions/artifacts@v4 # Updated actions path to handle latest standards
        with:
          name: AttendBot-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
